name: Claude Integration

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  process-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get context
        id: context
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue ? context.payload.issue.body : context.payload.comment.body;
            core.setOutput('comment', body);
            core.setOutput('repo', context.repo.owner + '/' + context.repo.repo);
            core.setOutput('branch', context.ref.replace('refs/heads/', ''));

      - name: Call Anthropic API
        id: claude
        uses: actions/github-script@v7
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        with:
          script: |
            const response = await fetch('https://api.anthropic.com/v1/messages', {
              method: 'POST',
              headers: {
                'x-api-key': process.env.ANTHROPIC_API_KEY,
                'anthropic-version': '2023-06-01',
                'content-type': 'application/json'
              },
              body: JSON.stringify({
                model: 'claude-3-5-sonnet-20241022',
                messages: [
                  {
                    role: 'system',
                    content: 'You are processing GitHub repository updates. Create or modify files based on the user request. Respond with a JSON object containing file paths and their content.'
                  },
                  {
                    role: 'user',
                    content: '${{ steps.context.outputs.comment }}'
                  }
                ],
                max_tokens: 4096
              })
            });
            
            const data = await response.json();
            if (data.error) {
              core.setFailed(data.error.message);
              return;
            }
            core.setOutput('result', data.content[0].text);

      - name: Create new branch
        run: |
          BRANCH_NAME="update/claude-$(date +%s)"
          git checkout -b $BRANCH_NAME
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Process Claude's response and create files
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const response = '${{ steps.claude.outputs.result }}';
            try {
              const files = JSON.parse(response);
              for (const [path, content] of Object.entries(files)) {
                fs.writeFileSync(path, content);
                console.log(`Created/updated file: ${path}`);
              }
            } catch (error) {
              core.setFailed(`Failed to process response: ${error.message}`);
            }

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update from Claude based on issue #${{ github.event.issue.number }}"
          git push origin ${{ env.BRANCH_NAME }}

      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Update from Claude',
              body: `Automated updates based on issue #${{ github.event.issue.number }}\n\nOriginal request: ${{ steps.context.outputs.comment }}`,
              head: process.env.BRANCH_NAME,
              base: '${{ github.event.repository.default_branch }}'
            });
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `Created PR: ${pr.data.html_url}\n\nPlease review the changes and let me know if you'd like any adjustments.`
            });
